spring:
  application:
    name: "Child"

server:
  servlet:
    context-path: /child-service
  port: 9002

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]